git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@defs.h
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@defs.h.blob
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@main.c
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@main.c.blob
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@memlayout.h
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@memlayout.h.blob
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@param.h
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@param.h.blob
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@riscv.h
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@riscv.h.blob
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@types.h
git restore --staged .ccls-cache/@Users@orange@code@MIT@xv6-labs-2021/kernel@types.h.blob
